"""Regression checks for first-release forks and project GitHub Pages URLs."""
import importlib.util
import io
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch
from urllib.parse import urlsplit
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("charts", ROOT / "scripts/generate-star-history.py")
charts = importlib.util.module_from_spec(spec)
spec.loader.exec_module(charts)

class Response(io.BytesIO):
    headers = {}

class PublicSiteTests(unittest.TestCase):
    def response(self, payload):
        return Response(json.dumps(payload).encode())

    def test_empty_stars_and_first_release(self):
        with patch.object(charts.urllib.request, "urlopen", return_value=self.response([])) as api:
            self.assertEqual(charts.fetch_star_dates("lalomalvi/OpenCADStudio", "test-token"), [])
            request = api.call_args.args[0]
            self.assertIn("lalomalvi/OpenCADStudio", request.full_url)
            self.assertEqual(request.get_header("Authorization"), "Bearer test-token")
        release = {"tag_name": "v1", "published_at": "2026-09-28T00:00:00Z", "assets": [{"download_count": 9}]}
        for payload in ([], [release]):
            with patch.object(charts.urllib.request, "urlopen", return_value=self.response(payload)):
                self.assertEqual(charts.fetch_release_downloads("lalomalvi/OpenCADStudio", None), [])
        older = {**release, "tag_name": "v0", "published_at": "2026-09-27T00:00:00Z"}
        with patch.object(charts.urllib.request, "urlopen", return_value=self.response([release, older])):
            result = charts.fetch_release_downloads("lalomalvi/OpenCADStudio", None)
            self.assertEqual([(r[0], r[2]) for r in result], [("v0", 9)])
        for locale in (ROOT / "site/locales").glob("*.json"):
            labels = json.loads(locale.read_text(encoding="utf-8"))
            for theme in charts.THEMES:
                for chart in ("stars", "downloads"):
                    tree = ET.fromstring(charts.render_svg("lalomalvi/OpenCADStudio", [], [], theme, chart, labels))
                    self.assertFalse(tree.findall(".//{http://www.w3.org/2000/svg}path"))
                    self.assertIn("0", " ".join(tree.itertext()))

    def test_aggregate_stars_without_personal_listing(self):
        week = {"week": 1790467200, "total": 3, "days": [0, 2, 0, 0, 0, 1, 0]}
        with patch.object(charts.urllib.request, "urlopen", return_value=self.response([week])) as api:
            dates = charts.fetch_star_dates("lalomalvi/OpenCADStudio", "test-token")
            self.assertIn("/stargazers/history?per_page=30", api.call_args.args[0].full_url)
            self.assertEqual(len(dates), 3)
            self.assertEqual(dates[0], dates[1])
            self.assertEqual((dates[2] - dates[0]).days, 4)
        for invalid in ({**week, "total": 4}, {**week, "days": [-1, 2, 0, 0, 0, 1, 0]}):
            with patch.object(charts.urllib.request, "urlopen", return_value=self.response([invalid])):
                with self.assertRaises(ValueError):
                    charts.fetch_star_dates("lalomalvi/OpenCADStudio", None)

    def test_project_paths_and_owned_origin(self):
        base = "https://lalomalvi.github.io/OpenCADStudio"
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory)
            (output / "app").mkdir()
            (output / "app/index.html").write_text('<html><head></head><body>App</body></html>', encoding="utf-8")
            env = {**os.environ, "OCS_SITE_URL": base, "OCS_SITE_REPOSITORY": "lalomalvi/OpenCADStudio", "PYTHONUTF8": "1"}
            subprocess.run(["sh", "scripts/assemble-site.sh", str(output)], cwd=ROOT, env=env, check=True)
            self.assertFalse((output / "CNAME").exists())
            self.assertIn(base + "/sitemap.xml", (output / "robots.txt").read_text())
            for page in output.glob("*/index.html"):
                html = page.read_text(encoding="utf-8")
                self.assertNotIn("www.opencadstudio.com", html)
                if page.parent.name == "app":
                    continue
                self.assertIn("https://github.com/lalomalvi/OpenCADStudio/releases", html)
                self.assertIn("Original project by Hakan Seven.", html)
                import re
                for target in re.findall(r'(?:src|href)=["\'](/[^"\']*)', html):
                    path = urlsplit(target).path
                    self.assertTrue(path.startswith("/OpenCADStudio/"), path)
                    relative = path.removeprefix("/OpenCADStudio/")
                    if relative.endswith("-history-dark.svg"):
                        continue # Charts are generated by the separate API step.
                    self.assertTrue((output / relative).exists(), path)
                manifest = json.loads((page.parent / "site.webmanifest").read_text(encoding="utf-8"))
                self.assertEqual(manifest["scope"], "/OpenCADStudio/")
                self.assertTrue(manifest["start_url"].startswith("/OpenCADStudio/"))
                self.assertEqual(manifest["shortcuts"][0]["url"], "/OpenCADStudio/app/")
            sitemap = ET.parse(output / "sitemap.xml")
            self.assertTrue(all(node[0].text.startswith(base + "/") for node in sitemap.getroot()))

if __name__ == "__main__":
    unittest.main()
